fix: the zoom button disabled in some cases #619
Greenstand/treetracker-web-map-client pull request #1213
Opened 2022-11-26 15:43 UTC by SuokN

# Description
Please check this decision
Fixes # the zoom button disabled in some cases #619

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
|![enabled](https://user-images.githubusercontent.com/19654801/204096964-2ff4c4b4-4a18-418e-9138-e429eea5c850.png)|![disabled2](https://user-images.githubusercontent.com/19654801/204096969-60315285-00b6-482d-9c49-eb162c8aea6a.png)|

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-02 20:36 UTC, RubenSmn requested changes
When you're on the `/top` page the initial zoom is already the max zoom but the button does not show that its disabled yet.

2022-12-02 20:36 UTC, RubenSmn commented on src/components/ZoomInOutButton.js
> +  const MOVE_END_EVENT = 'move-end';
We can get this from the `Map` itself

```js
import { Map } from 'treetracker-web-map-core';

Map.REGISTERED_EVENTS.MOVE_END
```

2022-12-02 20:36 UTC, RubenSmn commented on src/components/ZoomInOutButton.js
> +  });
We should add a dependency array here

2022-12-06 01:20 UTC, dadiorchen commented
@SuokN can you help fix the CI for unit tests? I checked the detail, it's a eslint error, should be easy to fix

2022-12-08 01:05 UTC, dadiorchen commented
@SuokN thank you!

2022-12-08 01:05 UTC, merged