fix: change link color with mode
Greenstand/treetracker-web-map-client pull request #1291
Opened 2022-12-17 00:24 UTC by ojafero

# Description

Link color will now change with theme mode.

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code

2022-12-19 11:01 UTC, RubenSmn requested changes

2022-12-19 11:01 UTC, RubenSmn commented on src/pages/500.js
> +import { useTheme } from '@emotion/react';
```js
import { useTheme } from '@mui/material/styles';
```

2022-12-22 08:37 UTC, RubenSmn requested changes
I think that an even better approach is to only use the `Link` component with a `sx` prop where we get the theme from. That way we don't need to use inline-styles and don't have a `a` tag in a `a` tag

2022-12-22 20:00 UTC, ojafero commented
@RubenSmn That arrangement is the recommended approach https://nextjs.org/docs/upgrading#link-component

2022-12-22 21:20 UTC, RubenSmn commented
Ah I see, but we're using the `Link` from `@mui/material` @ojafero

2023-02-03 12:40 UTC, RubenSmn approved these changes

2023-02-03 12:40 UTC, merged