fix(admin/theme): reset typography vals correctly
Greenstand/treetracker-web-map-client pull request #1359
Opened 2023-01-21 08:37 UTC by andrewsu31098

# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1353 
Added useEffect statement to reactively update TypographyInput when MUI theme was changed. 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |

[before](https://user-images.githubusercontent.com/48111116/213859084-516a2d71-c696-486c-b4be-3641e89959eb.PNG)
[after](https://user-images.githubusercontent.com/48111116/213859091-defe7d53-2905-4350-9d80-2a7ae98ad9ce.PNG)

# How Has This Been Tested?

- [x ] Cypress integration
- [ x] Cypress component tests

# Checklist:

- [x ] I have performed a self-review of my own code
- [ x] My changes generate no new warnings

2023-01-23 10:18 UTC, RubenSmn requested changes

2023-01-23 10:18 UTC, RubenSmn commented on src/components/playground/TypographyInput.js
> +  });
We're missing a dependency array here

2023-01-25 02:39 UTC, andrewsu31098 commented on src/components/playground/TypographyInput.js
> +  });
Got it, added in theme as a dependency

2023-01-25 09:20 UTC, RubenSmn approved these changes

2023-01-25 09:20 UTC, merged