Feat: cwm slider input
Greenstand/treetracker-web-map-client pull request #1653
Opened 2023-06-20 18:52 UTC by khalatevarun

# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes # (issue)

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
| "screenshot before" | "screenshot after" |

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-20 19:03 UTC, khalatevarun commented
@RubenSmn I have started with the development.
For now I have added changes to h1, could you please run it once on local and check if the basic functionality is working?

Listing down few questions here
* How should be the UI? - Currently, I have just added a new Slider input above TextInput and both the values will be in sync with single state variable. TextInput will not be editable since its to convey the value on the slider.

* Should we name this additional configs ( max, min, unit, step ) as `configs`? 

Would really appreciate your input on this @RubenSmn

2023-06-23 09:59 UTC, RubenSmn requested changes
Hi @khalatevarun great to see you working on this!

> How should be the UI? - Currently, I have just added a new Slider input above TextInput and both the values will be in sync with single state variable. TextInput will not be editable since its to convey the value on the slider.

I think the slider is just fine, it has a indicator of the current value. We might want to add some marks as a extra indication.

> Should we name this additional configs ( max, min, unit, step ) as configs?

Yes this is a good addition, it is easier to simply pass the props for the slider as `{...prop?.configs}`. But we also need to append the `unit` to the new value once it has changed. I would like to suggest something like this

```javascript
const { unit, ...restOfInputProps } = prop?.inputProps;

// ...

<Slider
  // ...
  {...restOfInputProps}
/>
```

I think a more descriptive name would be `inputProps` instead of `configs`.

2023-06-23 09:59 UTC, RubenSmn commented on src/components/playground/PropInput.js
> +    case CONFIG_INPUT_TYPES.FONT_SIZE:
No need to add a specific input type for the font size, in the config we can simply change the `inputType` to a `CONFIG_INPUT_TYPES.SLIDER`

2023-06-23 14:19 UTC, khalatevarun commented
https://github.com/Greenstand/treetracker-web-map-client/assets/68511458/9b5769e0-5bca-402e-be56-dc48358ac09e

@RubenSmn please check the latest changes in the video here, did you mean something like this?
I have also updated the changes in the PR

2023-06-26 11:40 UTC, RubenSmn requested changes
This looks really good @khalatevarun :ok_hand: very nice. I found two things we can improve upon:

- the initial value is not correctly displayed on the slider, the initial value of the h1 is `48px` and the slider has a initial value of `20px`
- the reset button is missing

As a reference you can take a look at the `TextInput` component :wink: I made a custom hook which allows you to access the default value.

2023-06-26 18:24 UTC, khalatevarun commented
Done, you can check now @RubenSmn

2023-06-29 09:36 UTC, RubenSmn reviewed
This is working very nice, I think we can update the config file and change the inputs to a slider input where suited!

2023-06-29 10:27 UTC, dadiorchen commented
Good job, guys!

2023-06-30 09:36 UTC, RubenSmn approved these changes
Thanks, awesome work!

2023-06-30 09:36 UTC, merged