Resolved Issue [#1742] Implemented MUI Tooltip for the UserAvatar com…
Greenstand/treetracker-web-map-client pull request #1743
Opened 2024-01-06 10:13 UTC by nitverse

# Description

Implemented MUI Tooltip in the `UserAvatar` component, enhancing the user experience by displaying the user's name on hover.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [x] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-08 09:31 UTC, dadiorchen commented
@nitverse thank you for you contribution, can you fix the eslint error in the ci:
<img width="957" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/0baeb8bf-2e42-4aae-b0c3-ce35d70d5ef0">

2024-01-31 03:28 UTC, DylanJG01 requested changes
The most pressing concern is fixing the tooltip to appear above the header.

2024-01-31 03:28 UTC, DylanJG01 commented on src/components/UserAvatar.js
> +    <Tooltip title={userName} arrow>
Currently the arrow tooltip will show up behind the header/banner of the website. This is likely due to the header having a z-index of '9999'.

![Screenshot 2024-01-30 191156](https://github.com/Greenstand/treetracker-web-map-client/assets/116132122/d14f45be-67e0-40ea-b98a-531ea95468eb)

 I am hesitant to suggest changing the header zindex to anything lower in the event it ruins the format in some place I'm unaware of. I am open to suggestions or ideas. @dadiorchen ?

2024-01-31 03:28 UTC, DylanJG01 commented on src/components/UserAvatar.js
> +              {userName}
We can change this to {userName ? userName[0] : null} to conform with the idea on line 8.

2026-04-16 19:17 UTC, closed without merging