mobile drawer
Greenstand/treetracker-web-map-client pull request #343
Opened 2021-12-04 08:51 UTC by dadiorchen

This is for the mobile layout with the drawer.

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202021-12-04%20at%204.47.24%20PM.mp4

Some code is for temporarily presenting. And the whole solution could be replaced with a better approach in the future.

2021-12-04 08:52 UTC, dadiorchen commented on src/pages/index.js
> +Homepage.isBLayout = true;
An ugly approach

2021-12-05 08:14 UTC, QuaidBartolomei commented on .eslintignore
> +.eslintrc.json
This has not been an issue for me in my other projects. I think the Typescript eslint parser I normally use excludes .json files but this project is Javascript and therefore uses a different parser so eslint will try to scan them if they are passed on the command line which lint-staged will do.

2021-12-05 08:16 UTC, QuaidBartolomei requested changes
![2021-12-05 00 13 03 localhost d4799b185e2c](https://user-images.githubusercontent.com/59486980/144739028-ddcd9f82-4520-4f1a-ab38-6dd5cd6780b4.png)

Something caused the homepage layout to change.

2021-12-06 03:01 UTC, dadiorchen commented
> ![2021-12-05 00 13 03 localhost d4799b185e2c](https://user-images.githubusercontent.com/59486980/144739028-ddcd9f82-4520-4f1a-ab38-6dd5cd6780b4.png)
> 
> Something caused the homepage layout to change.

thanks! fixed:
![image](https://user-images.githubusercontent.com/5744708/144780029-c5bbca27-0be9-4fa4-ae69-bb1abe7ebff6.png)

2021-12-06 03:56 UTC, QuaidBartolomei requested changes
![2021-12-05 19 37 18 localhost bb7603faefd8](https://user-images.githubusercontent.com/59486980/144784780-5698ab0d-a46b-467d-9bd2-2cc723815cf9.png)
Now there's a different layout issue

2021-12-06 03:56 UTC, QuaidBartolomei commented on src/components/Home.js
> +        <Box sx={{ height: 1000 }} />
```suggestion
```

2021-12-06 03:56 UTC, QuaidBartolomei commented on src/components/Home.js
> +        <Box sx={{ height: 1000 }} />
remove this and `height: '100%'` @ line 19 to fix the layout issue

2021-12-06 07:33 UTC, VWRoli approved these changes

2021-12-13 08:37 UTC, merged