feat: error/warning component #341
Greenstand/treetracker-web-map-client pull request #373
Opened 2021-12-17 04:03 UTC by arcadioramos

# Description

[comment]: # 'No alert/warning message was being displayed when start date was greater than end date.'

Fixes # error/warning component #341

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots 

[comment]: # 'Please include screenshots of your changes if relevant.'
Screen Recording 2021-12-16 at 20.42.46

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-17 07:06 UTC, VWRoli requested changes
Looks great! Give it some top and bottom margin though.
`sx={{ mt: 4, mb: 4 }}` will be fine.

2021-12-17 07:24 UTC, QuaidBartolomei commented
> Looks great! Give it some top and bottom margin though. `sx={{ mt: 4, mb: 4 }}` will be fine.

This can be shortened to `sx={{my: 4}}`

2021-12-17 07:33 UTC, QuaidBartolomei requested changes
The alert is looking good 👍.

package-lock.json should only change if the dependencies in package.json have changed. Can you remove the package-lock changes from the PR?

2021-12-17 07:33 UTC, QuaidBartolomei commented on src/components/common/Filter.js
> +// import log from 'loglevel';
this can just be deleted, imports can be easily replaced so there is no need to preserve them.
```suggestion
```

2021-12-17 07:56 UTC, QuaidBartolomei commented on src/components/common/Filter.js
> +                {/* I think you should use datepickers here :) */}
Switching the input to a [date-picker](https://mui.com/components/date-picker/)  could be posted as a separate issue

2021-12-17 15:59 UTC, arcadioramos commented
Changes recommended were made !!!

2021-12-17 17:12 UTC, VWRoli approved these changes

2021-12-17 21:51 UTC, QuaidBartolomei approved these changes
Good job, and thank you for updating the screenshot as well.

2021-12-27 02:25 UTC, QuaidBartolomei commented
@arcadioramos  It appears that there are some merge conflicts. You will need to pull the upstream changes on the web-map-site branch, then rebase this feature branch and resolve the merge conflicts.

2021-12-27 02:36 UTC, arcadioramos commented
I see @QuaidBartolomei , I'll work those conflicts in a while. Thank you🙌🏽

2021-12-27 04:27 UTC, arcadioramos commented
I've solved the conflict Quaid, can you re-confirm me it?

2021-12-28 01:25 UTC, dadiorchen commented
Thanks all, I think this is good enough for merge

2021-12-28 01:25 UTC, merged