Tag chip
Greenstand/treetracker-web-map-client pull request #464
Opened 2022-02-07 21:24 UTC by pratikmdhr

# Description

[comment]: # Added tag chip component for the continents. 

Fixes #427 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

Desktop (default state with no tag selection)
![desktop-default](https://user-images.githubusercontent.com/52301822/152873996-7ec4c9e9-f48e-4f50-b333-e80f6fc97043.png)

Desktop (selected state)
![desktop](https://user-images.githubusercontent.com/52301822/152873989-8219ef0d-e594-4503-9e67-5cd19d591016.png)

Mobile (default state with no tag selection)
![mobile-default](https://user-images.githubusercontent.com/52301822/152874037-8667187d-7928-4664-9266-e591e7d6a46b.png)

Mobile (selected state)
![mobile](https://user-images.githubusercontent.com/52301822/152874032-dbe78458-4c8d-4b8b-8812-726e5e12ddbe.png)

[comment]: # 'Please include screenshots of your changes if relevant.'

# How Has This Been Tested?

- [x] Cypress component tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

2022-02-09 09:13 UTC, VWRoli requested changes
Great job @pratikmdhr!

I only have some syntax tips for you so you can shorten your code.

___

In the sx prop we don't need to use the `[theme.breakpoints.down('md')]` syntax.
We can solve it with an array of values. The first value is xs, the second is sm, etc. This is much simpler and less code.
`padding: (t) => [t.spacing(2.75, 3.5), t.spacing(3.125, 4.5)],`
Same goes for gap and height properties.

___

https://github.com/Greenstand/treetracker-web-map-client/blob/157e55b3d6798a09bec4d09bfbe75e90a91a16a7/src/components/TagChips.js#L41-L43
Here you don't need `theme.palette` you can shorten the colors to `'common.white'` with the quote marks.

___

https://github.com/Greenstand/treetracker-web-map-client/blob/157e55b3d6798a09bec4d09bfbe75e90a91a16a7/src/components/TagChips.js#L37-L38
If we specify the paddings here, we can avoid setting the padding at 0 here. So we just write the paddings here, and remove it from above.
```
'& .MuiChip-label': {
              padding: (t) => [t.spacing(2.75, 3.5), t.spacing(3.125, 4.5)],
```

___

https://github.com/Greenstand/treetracker-web-map-client/blob/157e55b3d6798a09bec4d09bfbe75e90a91a16a7/src/components/TagChips.js#L27-L36
We can remove the `[theme.breakpoints.down('md')]` syntax from here too.
```
  sx={{
        width: '100%',
        gap: (t) => [t.spacing(4), t.spacing(5)],
        flexWrap: () => ['nowrap', 'wrap'],
        overflow: 'scroll',
        scrollbarWidth: 'none',
        '&::-webkit-scrollbar': { display: 'none' },
      }}
```

___
The same principles go for the container Box on the top page.

2022-02-09 17:11 UTC, pratikmdhr commented
@VWRoli thanks for letting me know about this syntax! looks much cleaner now

2022-02-09 17:24 UTC, VWRoli approved these changes

2022-02-10 00:40 UTC, dadiorchen commented
@pratikmdhr fantastic job!

2022-02-10 00:40 UTC, merged